on:
  workflow_dispatch: 

permissions:
  id-token: write
  contents: read

jobs: 
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Add Mask
        run: |
          echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - uses: actions/setup-python@v5
        with:
          python-version-file: pyproject.toml
      - uses: astral-sh/setup-uv@v7
      - run: uv sync --locked --all-extras --all-groups
      - run: make execute
        env:
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          KEY_PREFIX: ${{ github.repository_owner }}
          REFERENCE_CATEGORY: ${{ secrets.REFERENCE_CATEGORY }}
          BASE_URL_API_CONTENTFUL: ${{ secrets.BASE_URL_API_CONTENTFUL }}
          NOTION_DATA_SOURCE_ID: ${{ secrets.NOTION_DATA_SOURCE_ID }}
      - run: make upload-log
        env:
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          KEY_PREFIX: ${{ github.repository_owner }}
        if: always()
          
    